### ISSUE TITLE
Unhandled runtime exception: ConnectionResetError

### ISSUE THREAD

**Issue by Quinten0508** [samclane/LIFX-Control-Panel#146]
**Describe the bug**
The application does not launch successfully, instead showing the following error message:
```
Unhandled runtime exception: Traceback (most recent call last):
File "lifx_control_panel\__main__.pyw", line 335, in main
File "lifx_control_panel\__main__.pyw", line 101, in __init__
File "lifx_control_panel\__main__.pyw", line 167, in scan_for_lights
File "lifxlan\lifxlan.py", line 38, in get_devices
File "lifxlan\lifxlan.py", line 50, in discover_devices
File "lifxlan\lifxlan.py", line 259, in broadcast_with_resp
ConnectionResetError: [WinError 100541] An existing connection was forcibly closed by the remote host

Please report this at:
https://github.com/samclane/lifx_control_panel/issues
```

**To Reproduce**
1. Download v2.3.1 (latest) `lifx_control_panel.exe` from [release](https://github.com/samclane/LIFX-Control-Panel/releases/tag/untagged-717aee864f2b8cab90e9)
2. Open executable
3. See error

**Expected behavior**
I'd expect the application to simply launch/open, but it errors out. When `ok` is pressed, both the error window and the purple splashscreen close. Running the executable with administrator rights does not do anything.

**Screenshots**
error window:
![image](https://github.com/samclane/LIFX-Control-Panel/assets/55107945/f192784c-c3a3-42ed-8862-4b1c141b44a2)
error window and purple splashscreen(?) side-by-side. The error dialog can be dragged, the splashscreen cannot be moved.
![image](https://github.com/samclane/LIFX-Control-Panel/assets/55107945/1d628332-cda4-4233-aee8-0cea500056b8)

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: v2.3.1
 - OS: Windows 11 Pro 22H2 OS Build 22621.1928

**Please attach your logfile (lifx-control-panel.log)**
No logfile is generated, nor is there any console output when ran through a terminal (powershell/command prompt).

**Additional context**
none

**Comment by acortesg1300** [comment]
Hey @Quinten0508 I hope you are having a good day!
I was able to reproduce your issue by using the app with my Google One VPN;

![Bug reproduction](https://github.com/samclane/LIFX-Control-Panel/assets/129693697/1204aac3-aada-4caa-99f2-67332d29d8e1)

The issue no longer happens when turning off Google One VPN;

![Bug fix](https://github.com/samclane/LIFX-Control-Panel/assets/129693697/a1e981d8-bb90-4141-82fe-48ecfb3c1a5f)

If you are using a VPN, try turning it off before launching LIFX Control Panel.

Hope this helps shine some light on what might be the cause for anyone who knows how to fix this VPN incompatibility issue.

**Comment by Quinten0508** [comment]
Sorry for the late reply! Just got back home and confirmed that my VPN is turned off and the issue persists. I've also tried adding firewall rules (both in- and outbound) but without success.

**Comment by Quinten0508** [comment]
Nevermind, I had Tailscale enabled in the background. Disabling that fixed the connection issue :D

**Comment by Japh** [comment]
I'm also getting this error, with no VPN running.

**Comment by Japh** [comment]
Actually, I take that back. The symptoms appear the same, but the specific error I see is different. I will open a separate issue.

**Comment by samclane** [comment]
I was able to just recently fix this in #143 - compiled version will be up shortly.
