### ISSUE TITLE
AttributeError: 'Device' object has no attribute 'get_color'

### ISSUE THREAD

**Issue by Japh** [samclane/LIFX-Control-Panel#147]
**Describe the bug**
The application does not launch successfully, instead showing the following error messages:

Every launch attempt showed this message:
```
Unhandled runtime exception: Traceback (most recent call last):
  File "lifx_control_panel\__main__.pyw", line 335, in main
  File "lifx_control_panel\__main__.pyw", line 101, in __init__
  File "lifx_control_panel\__main__.pyw", line 190, in scan_for_lights
  File "lifxlan\frames.py", line 93, in __init__
  File "lifxlan\frames.py", line 148, in _get_light_info
AttributeError: 'Device' object has no attribute 'get_color'

Please report this at:
https://github.com/samclane/lifx_control_panel/issues
```

**To Reproduce**
1. Download v2.3.1 (latest) lifx_control_panel.exe from [release](https://github.com/samclane/LIFX-Control-Panel/releases/tag/untagged-717aee864f2b8cab90e9)
2. Open executable
3. See error

**Expected behavior**
I'd expect the application to simply launch/open, but it errors out. When `ok` is pressed, both the error window and the purple splashscreen close. Running the executable with administrator rights does not do anything.

**Screenshots**

Primary error I was seeing
![Screenshot 2023-10-05 093558](https://github.com/samclane/LIFX-Control-Panel/assets/237905/e3f3cb13-a255-4542-88cf-326d85651cc9)

I saw this error once also, but couldn't get it to appear a second time, so not sure what that one was caused by
![Screenshot 2023-10-05 093201](https://github.com/samclane/LIFX-Control-Panel/assets/237905/2526fed6-acfd-4565-99e8-b6ceb30e0ce8)

I saw this error once also, but couldn't get it to appear a second time, so not sure what that one was caused by
![Screenshot 2023-10-05 105005](https://github.com/samclane/LIFX-Control-Panel/assets/237905/cd6928e8-9e0d-4e16-aab6-4a499d0296ce)

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: 2.3.1
 - OS: Windows 10 Home Build 19045.3324

**Please attach your logfile (lifx-control-panel.log)**
No log files was generated, however I logged the output of the debug version of the release to the same filename which I provide here. This seems to indicate that the code does not cater to non-light devices (in this case, a LIFX switch), and doesn't fail gracefully.

[lifx-control-panel.log](https://github.com/samclane/LIFX-Control-Panel/files/12810934/lifx-control-panel.log)

**Additional context**
None.

**Comment by Japh** [comment]
I suspect the two one-off errors are unrelated, and due to some kind of collision or race condition failing hard. Each of those only happened once.

**Comment by samclane** [comment]
I've recently hardened the discovery process, which should have eliminated this error.
