### ISSUE TITLE
Unable to control my lights. Very glitchy.

### ISSUE THREAD

**Issue by superabhi44** [samclane/LIFX-Control-Panel#82]
"
Unhandled runtime exception: Traceback (most recent call last): 
File "lifx_control_panel\main_.pyw", line 750, in main
File "lifx_control_panel\main_.pyw", line 125, in_init_
File "lifx_control_panel\main_.pyw", line 216 in scan_for_lights
File "lifx_control_panel\main_.pyw", line 519 in_init
File "lifx_control_panel\utilities\utils.py", line 218, in str2list
ValueError: invalid literal for int() with base 10: 'full'
"
Can not get application to work properly with avg.screen mode functions. Once I click that button, the application breaks. Same with the dynamic and music modes. Basic color selection works, but thats all. 

I have razer chroma integration with lifx so I know my lights and network are capable of supporting the platform. I have also made sure this is not active will trying to run the program. 

I can upload my command prompt from the debug exe if it can help.

Hope this helps. Tnx.

**Comment by samclane** [comment]
@superabhi44 Could you upload your config.ini for me? Specifically the line:

`default_monitor = XXX`
