### ISSUE TITLE
Network connection closed error, unable to start

### ISSUE THREAD

**Issue by juicetin** [samclane/LIFX-Control-Panel#83]
**Describe the bug**
When starting the exe for version 1.7.6, I get a crash to desktop error

**To Reproduce**
1. Start .exe for version 1.7.6
2. Error window appears, with log file contents:
2020-05-27 18:42:21,898 - root - INFO - Logger initialized.
2020-05-27 18:42:22,015 - root.LifxFrame - INFO - Root logger initialized: root.LifxFrame
2020-05-27 18:42:22,016 - root.LifxFrame - INFO - Binary Version: 1.7.6
2020-05-27 18:42:22,016 - root.LifxFrame - INFO - Build time: 2020-02-08T14:54:32.841435
2020-05-27 18:42:22,038 - root - ERROR - [WinError 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "lifx_control_panel\__main__.pyw", line 750, in main
  File "lifx_control_panel\__main__.pyw", line 125, in __init__
  File "lifx_control_panel\__main__.pyw", line 182, in scan_for_lights
  File "lib\site-packages\lifxlan\lifxlan.py", line 42, in get_lights
  File "lib\site-packages\lifxlan\lifxlan.py", line 50, in discover_devices
  File "lib\site-packages\lifxlan\lifxlan.py", line 251, in broadcast_with_resp
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2020-05-27 18:42:48,903 - root - INFO - Logger initialized.
2020-05-27 18:42:48,989 - root.LifxFrame - INFO - Root logger initialized: root.LifxFrame
2020-05-27 18:42:48,989 - root.LifxFrame - INFO - Binary Version: 1.7.6
2020-05-27 18:42:48,989 - root.LifxFrame - INFO - Build time: 2020-02-08T14:54:32.841435
2020-05-27 18:42:49,011 - root - ERROR - [WinError 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "lifx_control_panel\__main__.pyw", line 750, in main
  File "lifx_control_panel\__main__.pyw", line 125, in __init__
  File "lifx_control_panel\__main__.pyw", line 182, in scan_for_lights
  File "lib\site-packages\lifxlan\lifxlan.py", line 42, in get_lights
  File "lib\site-packages\lifxlan\lifxlan.py", line 50, in discover_devices
  File "lib\site-packages\lifxlan\lifxlan.py", line 251, in broadcast_with_resp
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Expected behavior**
The application is expected to start

**Screenshots**
See attached 
[lifx-control-panel.log](https://github.com/samclane/LIFX-Control-Panel/files/4687629/lifx-control-panel.log)

**Desktop (please complete the following information):**
 - Lifx-Control-Panel Version: 1.7.6 (from releases tab on github)
 - OS: Windows 10 Pro 64 bit, Build 17763

**Please attach your logfile (lifx-control-panel.log)**
Attempt to reproduce the problem, then attach your `lifx_ctrl.log` file. This will give us the most information about what went wrong.

**Additional context**
![lifx-windows-error](https://user-images.githubusercontent.com/8791327/82998423-0f6cc780-a04b-11ea-925e-a2aaac356d6f.PNG)

**Comment by adrian-alpha** [comment]
When I had this issue, it was because my VPN was on. The app uses the LIFX LAN API so can only control your bulbs if it is on the same network.
